/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "home": [],
    "about": [],
    "blog": [],
    "work": [],
    "services": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}


export {};
